name: MMOPlugin
version: '${project.version}'
main: mmo.mmoplugin.MMOPlugin
api-version: '1.21'

commands:
  abilities:
    description: Opens the ability select menu
    usage: /abilities
    aliases: ab